# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  cloudsmith-npm:
    type: npm-registry
    url: https://npm.pkg.ofh.org.uk/npm/
    token: ${{ secrets.CLOUDSMITH_NPM_RO_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    registries:
      - cloudsmith-npm
